const headphones = [
	{
		title: "Apple EarPods",
		img: "images/image.png",
		price: 2300,
		rating: 4.7,
		id: 0,
	},
	{
		title: "Apple EarPods",
		img: "images/image-1.PNG",
		price: 2700,
		rating: 4.7,
		id: 1,
	},
	{
		title: "Apple BYZ S852I",
		img: "images/image-2.PNG",
		price: 3300,
		rating: 4.4,
		id: 2,
	},
	{
		title: "Apple EarPods",
		img: "images/image-3.png",
		price: 4300,
		rating: 4.7,
		id: 3,
	},
	{
		title: "Apple EarPods",
		img: "images/image-4.png",
		price: 7300,
		rating: 4.2,
		id: 4,
	},
	{
		title: "Apple EarPods",
		img: "images/image-5.png",
		price: 5350,
		rating: 4.1,
		id: 5,
	},
	{
		title: "Borofone BO4",
		img: "images/image-6.png",
		price: 3700,
		rating: 4.7,
		id: 6,
	},
	{
		title: "GERLAX GH-04",
		img: "images/image-7.png",
		price: 3700,
		rating: 4.7,
		id: 6,
	},
	{
		title: "Apple AirPods",
		img: "images/image-8.png",
		price: 3700,
		rating: 4.3,
		id: 6,
	},
	{
		title: "Beats",
		img: "images/image-9.jpg",
		price: 3700,
		rating: 4.1,
		id: 6,
	},
	{
		title: "Apple EarPods",
		img: "images/image-5.png",
		price: 5350,
		rating: 4.1,
		id: 5,
	},
	{
		title: "Borofone BO4",
		img: "images/image-6.png",
		price: 3700,
		rating: 4.7,
		id: 6,
	},
];

export { headphones };
